include: ["_pages"]

# Header data
name: Juan Ignacio Alonso Barba
job_title: Data Scientist
social_links:
  - url: mailto:jialonso@jialonso.com
    fa-icon: envelope
  - url: http://linkedin.com/in/jialonsobarba
    fa-icon: linkedin
  - url: http://github.com/jialonso
    fa-icon: github
